### ISSUE TITLE
TFS build task can't deal with spaces in folder names

### ISSUE THREAD

**Issue by timvandelockand** [marktaling/Augurk#34]
The TFS build task for publishing features to Augurk fails when the path to a feature file contains one or more spaces, i.e. if the feature file has the following path (on the build server):

`C:\Features\My feature category\MyFeature.feature`

The following exception will occur when trying to publish:

`System.IO.FileNotFoundException: Could not find file 'C:\Features\My'`

**Comment by marktaling** [comment]
At this moment the TFS 2015 Build Task is not part of Augurk (yet). It is a custom task for your team.
As such, it is not possible to fix it. (The commandline tool does support this scenario)
