### ISSUE TITLE
Search the scenarios and show a list of matching scenarios

### ISSUE THREAD

**Issue by harrynieboer** [marktaling/Augurk#5]
As a testmanager I would like to search for scenarios having a certain (combination of) tags so that I can view a list of those scenarios

e.g. a list of all scenario's tagged with @manual and @regressie

In search results, maintaining the grouping into solutions would be nice

**Comment by marktaling** [comment]
A small update on this issue:
I have decided to switch the storage from SQL Server to RavenDB. RavenDB allows for indexing the Json formatted data by multiple tags, something which comes in quite handy. The additional upside is that it can run embedded, so there is no need to install and maintain a separate database. (Licensing has been taken care of, as Hibernating Rhinos has been kind enough to provide an free license for this open source project.)

With the holidays having come to an end, I expect the switching of the database will take a couple of days. After which the search functionality should be easy to implement.

**Comment by harrynieboer** [comment]
Klinkt goed!

Vriendelijke groeten
Harry Nieboer

Op 4 jan. 2015 om 13:43 heeft marktaling <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


A small update on this issue:
I have decided to switch the storage from SQL Server to RavenDB. RavenDB allows for indexing the Json formatted data by multiple tags, something which comes in quite handy. The additional upside is that it can run embedded, so there is no need to install and maintain a separate database. (Licensing has been taken care of, as Hibernating Rhinos has been kind enough to provide an free license for this open source project.)

With the holidays having come to an end, I expect the switching of the database will take a couple of days. After which the search functionality should be easy to implement.

-
Reply to this email directly or view it on GitHub<https://github.com/marktaling/Augurk/issues/5#issuecomment-68631581>.

Op dit e-mailbericht is de disclaimer van Info Support van toepassing, zie http://www.infosupport.com/disclaimer
