### ISSUE TITLE
Command line tool to delete branch

### ISSUE THREAD

**Issue by harrynieboer** [marktaling/Augurk#9]
Sometimes a branch is not needed anymore. It would be handy to be able to delete that branch from Augurk. A command line tool would be ok.

**Comment by jmezach** [comment]
;) So, now that I'm a contributor I have to do all the work?

**Comment by marktaling** [comment]
Well, you were already working on the commandline tool. As such, it seems logical for you to take this request into consideration.

**Comment by jmezach** [comment]
;) Fair enough. I've already created a feature branch.
